### ISSUE TITLE
Really thank you for your self-giving help，Bre3n.But  there is something different with my thought. 

### ISSUE THREAD

**Issue by bohecsgo** [Bre3n/CSGO#1]
Really thank you for your self-giving help，Bre3n.But  there is something different with my thought. I just want  the display of avaters   on the  center of the  observes.There is lack of some codes  to create a box to place a img of players  into. But  I know little about the NodeJs ，can`t find the item to add the codes in.

The code I  think need to add as following

`<div id="observed" style="opacity: 1;">
this // <div id="obs_avatar"><img id="obs_img" src="/storage/avatar-1664369972483.png"></div>
          <div id="obs_lane1"></div>
          <div id="obs_lane2">
            <div id="obs_team"><img id="obs_img" src="/storage/76561199194027918"></div>
            <div  `
If it's not too much trouble, could you make it perfect in your free time？

**Comment by Bre3n** [comment]
Yeah, you're right. I changed the code and found an error when displaying avatars. I hope you will enjoy the new HUD with avatar! If no, please write here again.

**Comment by bohecsgo** [comment]
It`s so amazing huds that every element is completed.  It`s so kind of you,Bre3n. Really appreciate you ! I will learn more from  your codes,I hope I can do it by myself one day!
